const express = require('express');
const session = require('express-session');
const path = require('path');
const fs = require('fs');
const app = express();
const PORT = 3000;
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(session({ secret: 'tutor_sys_secret_2024', resave: false, saveUninitialized: false, cookie: { httpOnly: true, maxAge: 86400000 } }));
app.use(express.static(path.join(__dirname, 'public')));
const DATA_DIR = path.join(__dirname, 'data');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
function readJSON(fn) { const fp = path.join(DATA_DIR, fn); if (!fs.existsSync(fp)) return []; try { return JSON.parse(fs.readFileSync(fp, 'utf8')); } catch { return []; } }
function writeJSON(fn, d) { fs.writeFileSync(path.join(DATA_DIR, fn), JSON.stringify(d, null, 2), 'utf8'); }
function nextId() { return Date.now() + Math.floor(Math.random() * 9999); }
function now() { const d = new Date(); const p = n => String(n).padStart(2, '0'); return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`; }
(function initAdmin() { const users = readJSON('users.json'); if (!users.some(u => u.role === 'admin')) { users.push({ id: 1, username: 'admin', password: 'admin123', role: 'admin', nickname: '管理员', phone: '13800000000', createdAt: now() }); writeJSON('users.json', users); } })();
app.post('/api/auth/register', (req, res) => { const { username, password, role, nickname, phone } = req.body; if (!username || !password || !role || !nickname || !phone) return res.json({ ok: false, msg: '缺少必填字段' }); if (username.length < 4 || username.length > 20) return res.json({ ok: false, msg: '用户名4-20位' }); if (!/^[a-zA-Z0-9_]+$/.test(username)) return res.json({ ok: false, msg: '用户名仅限字母数字下划线' }); if (password.length < 6) return res.json({ ok: false, msg: '密码至少6位' }); if (!/^1\d{10}$/.test(phone)) return res.json({ ok: false, msg: '手机号格式错误' }); const users = readJSON('users.json'); if (users.some(u => u.username === username)) return res.json({ ok: false, msg: '用户名已存在' }); users.push({ id: nextId(), username, password, role, nickname, phone, createdAt: now() }); writeJSON('users.json', users); res.json({ ok: true, msg: '注册成功' }); });
app.post('/api/auth/login', (req, res) => { const { username, password } = req.body; if (!username || !password) return res.json({ ok: false, msg: '请输入用户名和密码' }); const user = readJSON('users.json').find(u => u.username === username && u.password === password); if (!user) return res.json({ ok: false, msg: '用户名或密码错误' }); req.session.userId = user.id; res.json({ ok: true, user: { id: user.id, username: user.username, role: user.role, nickname: user.nickname } }); });
app.post('/api/auth/logout', (req, res) => { req.session.destroy(() => res.json({ ok: true })); });
app.get('/api/auth/me', (req, res) => { if (!req.session.userId) return res.json({ ok: false }); const user = readJSON('users.json').find(u => u.id === req.session.userId); if (!user) return res.json({ ok: false }); res.json({ ok: true, user: { id: user.id, username: user.username, role: user.role, nickname: user.nickname } }); });
function requireAuth(req, res, next) { if (!req.session.userId) return res.status(401).json({ ok: false, msg: '未登录' }); next(); }
function requireRole(role) { return (req, res, next) => { if (!req.session.userId) return res.status(401).json({ ok: false, msg: '未登录' }); const user = readJSON('users.json').find(u => u.id === req.session.userId); if (!user || user.role !== role) return res.status(403).json({ ok: false, msg: '无权限' }); next(); }; }
app.get('/api/student/listings', requireAuth, (req, res) => { const list = readJSON('students.json').filter(l => l.userId === req.session.userId); res.json({ ok: true, data: list }); });
app.post('/api/student/listings', requireRole('student'), (req, res) => { const { subjects, grades, districts, timeSlots, certNames } = req.body; if (!subjects || !subjects.length) return res.json({ ok: false, msg: '请选择科目' }); if (!grades || !grades.length) return res.json({ ok: false, msg: '请选择年级' }); if (!districts || !districts.length) return res.json({ ok: false, msg: '请选择地区' }); if (!timeSlots || !timeSlots.length) return res.json({ ok: false, msg: '请选择空闲时间' }); const list = readJSON('students.json'); list.push({ id: nextId(), userId: req.session.userId, subjects, grades, districts, timeSlots, certNames: certNames || [], status: 'pending', createdAt: now() }); writeJSON('students.json', list); res.json({ ok: true, msg: '提交成功，等待审核' }); });
app.put('/api/student/listings/:id', requireRole('student'), (req, res) => { const list = readJSON('students.json'); const idx = list.findIndex(l => l.id == req.params.id && l.userId === req.session.userId); if (idx === -1) return res.json({ ok: false, msg: '不存在' }); const { subjects, grades, districts, timeSlots, certNames } = req.body; Object.assign(list[idx], { subjects, grades, districts, timeSlots, certNames: certNames || [], status: 'pending' }); writeJSON('students.json', list); res.json({ ok: true, msg: '已更新' }); });
app.delete('/api/student/listings/:id', requireAuth, (req, res) => { const list = readJSON('students.json'); const idx = list.findIndex(l => l.id == req.params.id && l.userId === req.session.userId); if (idx === -1) return res.json({ ok: false, msg: '不存在' }); list.splice(idx, 1); writeJSON('students.json', list); res.json({ ok: true }); });
app.get('/api/parent/listings', requireAuth, (req, res) => { const list = readJSON('parents.json').filter(l => l.userId === req.session.userId); res.json({ ok: true, data: list }); });
app.post('/api/parent/listings', requireRole('parent'), (req, res) => { const { subjects, grades, district, pay, timeSlots } = req.body; if (!subjects || !subjects.length) return res.json({ ok: false, msg: '请选择科目' }); if (!grades || !grades.length) return res.json({ ok: false, msg: '请选择年级' }); if (!district) return res.json({ ok: false, msg: '请选择地区' }); if (!pay || pay <= 0) return res.json({ ok: false, msg: '请输入有效报酬' }); if (!timeSlots || !timeSlots.length) return res.json({ ok: false, msg: '请选择授课时间' }); const list = readJSON('parents.json'); list.push({ id: nextId(), userId: req.session.userId, subjects, grades, district, pay: Number(pay), timeSlots, status: 'pending', createdAt: now() }); writeJSON('parents.json', list); res.json({ ok: true, msg: '提交成功，等待审核' }); });
app.put('/api/parent/listings/:id', requireRole('parent'), (req, res) => { const list = readJSON('parents.json'); const idx = list.findIndex(l => l.id == req.params.id && l.userId === req.session.userId); if (idx === -1) return res.json({ ok: false, msg: '不存在' }); const { subjects, grades, district, pay, timeSlots } = req.body; Object.assign(list[idx], { subjects, grades, district, pay: Number(pay), timeSlots, status: 'pending' }); writeJSON('parents.json', list); res.json({ ok: true, msg: '已更新' }); });
app.delete('/api/parent/listings/:id', requireAuth, (req, res) => { const list = readJSON('parents.json'); const idx = list.findIndex(l => l.id == req.params.id && l.userId === req.session.userId); if (idx === -1) return res.json({ ok: false, msg: '不存在' }); list.splice(idx, 1); writeJSON('parents.json', list); res.json({ ok: true }); });
app.get('/api/admin/pending', requireRole('admin'), (req, res) => { const students = readJSON('students.json').filter(l => l.status === 'pending').map(l => ({ ...l, _type: 'student' })); const parents = readJSON('parents.json').filter(l => l.status === 'pending').map(l => ({ ...l, _type: 'parent' })); const users = readJSON('users.json'); const all = [...students, ...parents].map(l => { const u = users.find(x => x.id === l.userId); return { ...l, publisher: u ? u.nickname : '未知' }; }); res.json({ ok: true, data: all }); });
app.get('/api/admin/all', requireRole('admin'), (req, res) => { const students = readJSON('students.json').map(l => ({ ...l, _type: 'student' })); const parents = readJSON('parents.json').map(l => ({ ...l, _type: 'parent' })); const users = readJSON('users.json'); const all = [...students, ...parents].sort((a, b) => a.createdAt < b.createdAt ? 1 : -1).map(l => { const u = users.find(x => x.id === l.userId); return { ...l, publisher: u ? u.nickname : '未知' }; }); res.json({ ok: true, data: all }); });
app.post('/api/admin/audit', requireRole('admin'), (req, res) => { const { type, id, action, comment } = req.body; const fn = type === 'student' ? 'students.json' : 'parents.json'; const list = readJSON(fn); const idx = list.findIndex(l => l.id == id); if (idx === -1) return res.json({ ok: false, msg: '不存在' }); list[idx].status = action === 'approve' ? 'approved' : 'rejected'; list[idx].auditComment = comment || ''; list[idx].auditTime = now(); writeJSON(fn, list); res.json({ ok: true, msg: action === 'approve' ? '已通过' : '已拒绝' }); });
app.get('/api/public/tutors', (req, res) => { let list = readJSON('students.json').filter(l => l.status === 'approved'); const { subject, grade } = req.query; if (subject) list = list.filter(l => l.subjects.includes(subject)); if (grade) list = list.filter(l => l.grades.includes(grade)); const users = readJSON('users.json'); const data = list.map(l => { const u = users.find(x => x.id === l.userId); return { subjects: l.subjects, grades: l.grades, districts: l.districts, timeSlots: l.timeSlots, publisher: u ? u.nickname : '未知' }; }); res.json({ ok: true, data }); });
app.get('/api/public/needs', (req, res) => { let list = readJSON('parents.json').filter(l => l.status === 'approved'); const { subject, grade, maxPay } = req.query; if (subject) list = list.filter(l => l.subjects.includes(subject)); if (grade) list = list.filter(l => l.grades.includes(grade)); if (maxPay && Number(maxPay) > 0) list = list.filter(l => l.pay <= Number(maxPay)); const users = readJSON('users.json'); const data = list.map(l => { const u = users.find(x => x.id === l.userId); return { subjects: l.subjects, grades: l.grades, timeSlots: l.timeSlots, pay: l.pay, district: l.district, publisher: u ? u.nickname : '未知' }; }); res.json({ ok: true, data }); });
app.get('/api/statistics', (req, res) => { const ss = readJSON('students.json').filter(l => l.status === 'approved'); const ps = readJSON('parents.json').filter(l => l.status === 'approved'); const sb = {};['语文', '数学', '英语', '物理', '化学'].forEach(s => sb[s] = 0); const sg = {};['小学', '初中', '高中'].forEach(g => sg[g] = 0); const dp = {};['上午', '下午', '晚上'].forEach(p => dp[p] = 0); ps.forEach(p => { p.subjects.forEach(s => { if (sb[s] !== undefined) sb[s]++; }); p.grades.forEach(g => { if (sg[g] !== undefined) sg[g]++; }); (p.timeSlots || []).forEach(ts => { const pi = parseInt(ts.split('-')[1], 10); if (pi >= 0 && pi < 3) dp[['上午', '下午', '晚上'][pi]]++; }); }); const ssb = {};['语文', '数学', '英语', '物理', '化学'].forEach(s => ssb[s] = 0); const ssg = {};['小学', '初中', '高中'].forEach(g => ssg[g] = 0); ss.forEach(s => { s.subjects.forEach(sub => { if (ssb[sub] !== undefined) ssb[sub]++; }); s.grades.forEach(g => { if (ssg[g] !== undefined) ssg[g]++; }); }); res.json({ ok: true, data: { demand: { subjects: sb, grades: sg, periods: dp }, supply: { subjects: ssb, grades: ssg } } }); });
app.get('/api/home/stats', (req, res) => { const users = readJSON('users.json'); const students = readJSON('students.json'); const parents = readJSON('parents.json'); res.json({ ok: true, data: { studentCount: users.filter(u => u.role === 'student').length, parentCount: users.filter(u => u.role === 'parent').length, pendingCount: students.filter(l => l.status === 'pending').length + parents.filter(l => l.status === 'pending').length, approvedCount: students.filter(l => l.status === 'approved').length + parents.filter(l => l.status === 'approved').length } }); });
app.listen(PORT, () => console.log(`家教系统后端已启动: http://localhost:${PORT}`));
